version: "3.8"
services:
  backend:
    container_name: pos
    build: .
    ports:
      - "3002:3000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod
