name: Deploy

on:
    workflow_dispatch:
    push:
      tags:
         - "v*"

jobs:
  deployEpitech:
    uses: ./.github/workflows/deployEPITECH.yaml

  deployVPS:
    uses: ./.github/workflows/deployVPS.yaml
    with:
      tag: ${{ github.ref_name }}