name: Development

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["main", "dev"]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/linter.yaml
  build:
    name: "Build and test"
    needs: lint
    uses: ./.github/workflows/buildAndTest.yaml